Repository eslint/typescript-eslint-parser, pull requests merged in 2018-11, with the labels that each got.

#530 Docs: add options to README
  README.md
Labels: triage

#538 Breaking: typescript-estree v5
  README.md
  package.json
  tests/lib/__snapshots__/basics.js.snap
  tests/lib/__snapshots__/ecma-features.js.snap
  tests/lib/__snapshots__/jsx.js.snap
  tests/lib/__snapshots__/tsx.js.snap
  tests/lib/__snapshots__/typescript.js.snap
  tests/lib/basics.js
  tests/lib/comments.js
  tests/lib/ecma-features.js
  tests/lib/jsx.js
  tests/lib/tsx.js
  tests/lib/typescript.js
  tools/test-utils.js
Labels: breaking

#541 Breaking: make eslint a peerDep/devDep
  package.json
Labels: breaking

#543 Breaking: switch 'jsx' option by filename (fixes #517)
  README.md
  parser.js
  tests/lib/tsx.js
Labels: breaking, enhancement

#544 Breaking: make 'useJSXTextNode:true' by default
  README.md
  parser.js
  tests/lib/__snapshots__/comments.js.snap
Labels: breaking

#540 Update: add proper scope analysis (fixes #535)
  analyze-scope.js
  package.json
  parser.js
  tests/fixtures/scope-analysis/535.ts
  tests/fixtures/scope-analysis/abstract-class.ts
  tests/fixtures/scope-analysis/class-properties.ts
  tests/fixtures/scope-analysis/computed-properties-in-interface.ts
  tests/fixtures/scope-analysis/computed-properties-in-type.ts
  tests/fixtures/scope-analysis/declare-function.ts
  tests/fixtures/scope-analysis/declare-global.ts
  tests/fixtures/scope-analysis/declare-module.ts
  tests/fixtures/scope-analysis/decorators.ts
  tests/fixtures/scope-analysis/enum.ts
  tests/fixtures/scope-analysis/function-overload-2.ts
  tests/fixtures/scope-analysis/function-overload.ts
  tests/fixtures/scope-analysis/ignore-type-only-stuff.ts
  tests/fixtures/scope-analysis/method-overload.ts
  tests/fixtures/scope-analysis/namespace.ts
  tests/fixtures/scope-analysis/type-annotations.ts
  tests/fixtures/scope-analysis/type-assertions.ts
  tests/fixtures/scope-analysis/typeof-in-assertions.ts
  tests/fixtures/scope-analysis/typeof-in-call-signature.ts
  tests/fixtures/scope-analysis/typeof-in-return-type.ts
  tests/fixtures/scope-analysis/typeof-in-type-parameters.ts
  tests/fixtures/scope-analysis/typeof-in-var.ts
  tests/fixtures/scope-analysis/typeof.ts
  tests/lib/__snapshots__/scope-analysis.js.snap
  tests/lib/basics.js
  tests/lib/scope-analysis.js
  visitor-keys.js
Labels: bug

#549 Upgrade: eslint-release v1.2.0
  package.json
Labels: triage

#551 Fix: wrong reference on TSQualifiedName (fixes #550)
  analyze-scope.js
  tests/lib/scope-analysis.js
Labels: bug

#556 Fix: crash in no-unused-vars when using enum
  tests/fixtures/scope-analysis/enum-string.ts
  tests/lib/__snapshots__/scope-analysis.js.snap
  visitor-keys.js
Labels: triage

#565 Fix: visiting typeParameters in expressions
  analyze-scope.js
  tests/fixtures/scope-analysis/expression-type-parameters.ts
  tests/lib/__snapshots__/scope-analysis.js.snap
  visitor-keys.js
Labels: triage

#561 Fix: visiting superTypeParameters in classes
  analyze-scope.js
  tests/fixtures/scope-analysis/class-supper-type.ts
  tests/lib/__snapshots__/scope-analysis.js.snap
  visitor-keys.js
Labels: triage

#562 Fix: visiting implements in classes
  analyze-scope.js
  tests/fixtures/scope-analysis/class-implements.ts
  tests/lib/__snapshots__/scope-analysis.js.snap
  visitor-keys.js
Labels: triage

#571 Fix: scope for TSImportEqualsDeclaration
  analyze-scope.js
  tests/fixtures/scope-analysis/import-equals.ts
  tests/lib/__snapshots__/scope-analysis.js.snap
  visitor-keys.js
Labels: bug
